services:
  - type: web
    name: ai-campus-backend
    env: node
    plan: free
    region: ohio
    rootDir: backend
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
